name: CI/CD for Python App

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          pip install -r requirements.txt
          pytest
        env:
          PYTHONPATH: ${{ github.workspace }}

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker build -t my-python-app .

      - run: echo "Деплой виконано успішно (імітація)"

